[workspace]
resolver = "2"
members = [ "boid_simulation",
    "ecs_and_queries"
, "physarum_simulation", "plugins_and_resources"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
